/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const path = require("path");
const { readdir, readFile, writeFile } = require("fs/promises");

const app = express();

const filePath = path.join(__dirname, "todos.json");
let todos = [];

async function readTodos() {
  try {
    const todo = await readFile(filePath, "utf-8");
    todos = JSON.parse(todo);
  } catch (error) {
    console.error("Error reading todos file:", error);
  }
}

readTodos();

app.use(bodyParser.json());

// Get all Todos
app.get("/todos", async (req, res) => {
  try {
    return res.status(200).json(todos);
  } catch (error) {
    console.error("Error:", error);
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// Get few todos that match the id
app.get("/todos/:id", async (req, res) => {
  try {
    const todoByID = todos.find((file) => file.id === req.params.id);
    if (todoByID === undefined) {
      return res.status(404).json({ error: "Todo not found" });
    }
    return res.status(200).json(todoByID);
  } catch (error) {
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

// Create a new todo item in todo.json file.
app.post("/todos", async (req, res) => {
  try {
    const todo = {
      id: Math.floor(Math.random() * 1000),
      title: req.body.title,
      completed: req.body.completed,
      description: req.body.description,
    };
    todos.push(todo);
    await writeFile(filePath, JSON.stringify(todos));
    res.status(201).json({ message: `Created todo with the ID: ${todo.id}` });
  } catch (error) {
    return res.status(500).json({ error: error });
  }
});

app.put("/todos/:id", async (req, res) => {
  try {
    const todoByID = todos.find((todo) => todo.id === parseInt(req.params.id));
    if (todoByID == undefined) {
      return res.status(404).json({ error: "Todo not found" });
    }
    todoByID.title = req.body.title;
    todoByID.completed = req.body.completed;
    todoByID.description = req.body.description;

    await writeFile(filePath, JSON.stringify(todos));
    res
      .status(200)
      .json({ message: `Updated todo with the ID: ${req.params.id}` });
  } catch (error) {
    return res.status(500).json({ error: "Internal Server Error" });
  }
});

app.delete("/todos/:id", async (req, res) => {
  try {
    const index = todos.findIndex(
      (todo) => todo.id === parseInt(req.params.id)
    );
    if (index === -1) {
      return res.status(404).json({ error: "Todo not found" });
    }
    const deletedTodo = todos.splice(index, 1)[0];
    await writeFile(filePath, JSON.stringify(todos));
    return res.status(200).json({ message: `Deleted todo with ID` });
  } catch (error) {
    return res.status(500).json({ error: `Internal Server Error` });
  }
});

app.use((req, res) => {
  return res.status(404).json({ error: "Route not found" });
});

module.exports = app;
